// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzarlYK-q0LCpmcZI2YOTAUZFnPXrRGPw',
    appId: '1:4946936630:android:29b3a40f6328870e9ea997',
    messagingSenderId: '4946936630',
    projectId: 'pg-app-8370b',
    storageBucket: 'pg-app-8370b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB51fKhafs8kATQ1PDo9z_teRbS5IpOfgs',
    appId: '1:4946936630:ios:60216787c5f2cc409ea997',
    messagingSenderId: '4946936630',
    projectId: 'pg-app-8370b',
    storageBucket: 'pg-app-8370b.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOSytUc9xrZYP-jQpEI5i7Ds036u_iKcE',
    appId: '1:4946936630:web:a2007819a8e41b2d9ea997',
    messagingSenderId: '4946936630',
    projectId: 'pg-app-8370b',
    authDomain: 'pg-app-8370b.firebaseapp.com',
    storageBucket: 'pg-app-8370b.firebasestorage.app',
    measurementId: 'G-W49CS06DW9',
  );

}