// lib/main.dart
import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'package:untitled/routes.dart';
import 'package:untitled/screens/AdminScreens/admin_home.dart';
import 'package:untitled/screens/splash_screen/splash_screen.dart';
import 'package:untitled/screens/login_screen/login_screen.dart';
import 'package:untitled/screens/login_screen/signup_screen.dart';
import 'package:untitled/screens/home_screen/home_screen.dart';
import 'package:untitled/screens/AdminScreens/admin_home.dart'; // <-- IMPORTANT
import 'package:untitled/theme.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase before runApp
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(MyApp());
}

// ---- ADMIN EMAIL LIST (Option A) ----
const List<String> adminEmails = [
  "aniket.ashok2022@vitstudent.ac.in",
  "admin2@example.com",
];

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Sizer(builder: (context, orientation, device) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Aryan PG',
        theme: CustomTheme().baseTheme,
        routes: routes,
        home: AuthGate(),
      );
    });
  }
}

class AuthGate extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // waiting for Firebase
        if (snapshot.connectionState == ConnectionState.waiting) {
          return SplashScreen();
        }

        // NOT signed in → go to login/signup
        if (!snapshot.hasData) {
          return SignupScreen();
        }

        // SIGNED IN → check admin or client
        final user = snapshot.data!;
        final email = (user.email ?? "").toLowerCase();

        final isAdmin = adminEmails
            .map((e) => e.toLowerCase())
            .contains(email);

        if (isAdmin) {
          return AdminHome(); // <-- ADMIN SIDE HOME
        } else {
          return HomeScreen(); // <-- CLIENT SIDE HOME
        }
      },
    );
  }
}
